### ISSUE TITLE
Could you share the source video of "City Drive"?

### ISSUE THREAD

**Issue by wsp123** [JunshengFu/vehicle-detection#8]
A colleague of my mentor asked me to do some modifications on your work and present a demo for him to show off or whatever.Could you please share your source video of "City Drive"?That would help me a lot.

**Comment by JunshengFu** [comment]
Here you go: https://www.youtube.com/watch?v=jso30o_2r5Y

**Comment by wsp123** [comment]
@JunshengFu Thanks a lot, I really appreciate it. And btw, your work is marvelous. :-)

**Comment by JunshengFu** [comment]
@wsp123 Thank you and good luck with your demo
